CREATE TABLE superstore (
    row_id INTEGER PRIMARY KEY,
    
    order_id VARCHAR(20) NOT NULL,
    order_date DATE NOT NULL,
    ship_date DATE NOT NULL,
    
    ship_mode VARCHAR(50),
    
    customer_id VARCHAR(20) NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    
    segment VARCHAR(50),
    
    country VARCHAR(50),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    region VARCHAR(50),
    
    product_id VARCHAR(50) NOT NULL,
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_name VARCHAR(255),
    
    sales NUMERIC(10,2) NOT NULL,
    quantity INTEGER NOT NULL,
    discount NUMERIC(4,2) NOT NULL,
    profit NUMERIC(10,2) NOT NULL
);

SELECT * FROM superstore;

COPY superstore (row_id, order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, country, city, state, postal_code, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit)
FROM 'E:\All My Study\Data Analytics Projects\Sales Performance Dashboard\01 data\Sample - Superstore - csv3.csv'
DELIMITER ','
CSV HEADER;

SELECT * FROM superstore;

SELECT * FROM superstore
ORDER BY row_id;

-- Query 1: Total Sales and Profit
SELECT
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore;

-- Total Sales  = $2,297,201.07
-- Total Profit = $286,397.79

-- Query 2: Region Analysis
SELECT
    region,
    ROUND(SUM(sales),2) AS sales,
    ROUND(SUM(profit),2) AS profit
FROM superstore
GROUP BY region
ORDER BY sales DESC;

-- Is a profit of $286k good on $2.3M sales?
-- To answer that, calculate Profit Margin.
SELECT
    ROUND(SUM(profit)/SUM(sales)*100,2) AS profit_margin_pct
FROM superstore;

-- Analyst Thinking
-- West has highest sales.

-- A good analyst asks:
-- Which region is most efficient?
-- Let's calculate profit margin by region.

SELECT
    region,
    ROUND(SUM(sales),2) AS sales,
    ROUND(SUM(profit),2) AS profit,
    ROUND((SUM(profit)/SUM(sales))*100,2) AS profit_margin_pct
FROM superstore
GROUP BY region
ORDER BY profit_margin_pct DESC;

-- "What insight did you derive?"
-- Weak Answer
	-- West has highest sales.

-- Strong Answer
	-- West contributes approximately 32% of company sales and generates the highest absolute profit, 
	-- making it the most important region for revenue growth initiatives.

-- Learn GROUP BY Properly
SELECT
    region,
    SUM(sales)
FROM superstore
GROUP BY region;

-- Take all 9994 rows
-- Group rows by region
-- Calculate total sales for each group

-- What We're Looking For
-- most profitable category.
-- Which category earns the most money?
SELECT
    category,
    ROUND(SUM(sales),2) AS sales,
    ROUND(SUM(profit),2) AS profit
FROM superstore
GROUP BY category
ORDER BY profit DESC;

-- Which sub-categories are hurting the business?
SELECT
    sub_category,
    ROUND(SUM(profit),2) AS profit
FROM superstore
GROUP BY sub_category
ORDER BY profit ASC;

-- What do those rows represent?
-- How many order-line records were generated by each region?
SELECT region, COUNT(*)
FROM superstore
GROUP BY region;

-- Analyst Thinking
-- A single customer can place multiple orders.
-- This tells us:
	-- Customers place multiple orders
	-- Orders contain multiple products
	-- That's actually useful business information.
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT customer_id) AS total_customers
FROM superstore;

-- Average_orders_per_customer
-- Average_products_per_order
-- multiplied by 1.0 to ensure float/decimal division
-- Why is COUNT(*) different from COUNT(DISTINCT order_id)?
	-- COUNT(*) counts all order-line records, while COUNT(DISTINCT order_id) counts unique orders. 
	-- Since a single order can contain multiple products, the number of rows is higher than the number of unique orders. 
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT customer_id) AS total_customers, 
    ROUND(COUNT(DISTINCT order_id) * 1.0 / COUNT(DISTINCT customer_id),2) AS Average_orders_per_customer, 
    ROUND(COUNT(*) * 1.0 / COUNT(DISTINCT order_id),2) AS Average_products_per_order
FROM superstore;

SELECT * FROM superstore
ORDER BY row_id;

-- Show only categories whose total profit is greater than $50,000.

SELECT
    category,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY category
HAVING SUM(profit) > 50000
ORDER BY total_profit DESC;

-- Which products are losing money?
-- discovered that Tables is a loss-making sub-category. What would you do next?
	-- I would analyze discount levels, sales volume, profit margin, and regional performance to identify the drivers of the losses. 
	-- Then I would recommend pricing, supplier, or discounting changes based on the findings.
SELECT
    sub_category,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY sub_category
HAVING SUM(profit) < 0
ORDER BY total_profit;

-- identify:
	-- The bottom 3 sub-categories by profit.
	-- Whether any of them have high sales but low/negative profit.
SELECT
    sub_category,
    ROUND(SUM(sales),2) AS sales,
    ROUND(SUM(profit),2) AS profit
FROM superstore
GROUP BY sub_category
ORDER BY profit ASC;

-- find:
	-- Which sub-category has the worst profit margin %?
		-- Sub_category "Tables", Sales 206965.68, profit -17725.59, profit_margin -8.56
	-- Is it also the one with the highest loss?
		-- yes
	-- What business explanation can you think of?
		-- Tables generated over $206,000 in sales but produced a loss of $17,725, resulting in a negative profit margin. 
		-- I would investigate whether high discounts, high shipping costs, supplier pricing, or poor regional performance
		-- are contributing to the losses. Based on the findings, I would recommend pricing adjustments, discount optimization, 
		-- or supplier renegotiation.
SELECT
    sub_category,
    ROUND(SUM(sales),2) AS sales,
    ROUND(SUM(profit),2) AS profit,
    ROUND((SUM(profit)/SUM(sales))*100,2) AS profit_margin_pct
FROM superstore
GROUP BY sub_category
ORDER BY profit_margin_pct;

-- CTEs (Common Table Expressions)
-- Let's find categories with profit above the average category profit.
-- Why use a CTE instead of a subquery?
	-- CTEs improve readability and make complex queries easier to understand and maintain. 
	-- They also allow intermediate results to be reused within the same query.
-- Which categories were above average profit?
	-- "Office Supplies"	122490.88
	-- "Technology"     	145455.66
-- In your own words, what did the CTE do?
	-- It helped me find categories with profit above the average category profit.
WITH category_profit AS (
    SELECT
        category,
        SUM(profit) AS total_profit
    FROM superstore
    GROUP BY category
)
SELECT *
FROM category_profit
WHERE total_profit >
(
    SELECT AVG(total_profit)
    FROM category_profit
);

-- RANK() 
	-- Gaps exist.
	-- Who is ranked #1?
		-- Customer_name  "Sean Miller",  total_sales 25043.07,  Sales_Rank 1
	-- Are there any ties in the top 10?
		-- No
	-- In your own words, what is the difference between GROUP BY and RANK()?
		-- GROUP BY takes many rows and aggregates them.
		-- GROUP BY reduces many rows into summary rows.
			-- Final, GROUP BY aggregates rows into groups and calculates summary metrics such as total sales.
		-- RANK doesn't reduce rows. It takes the summarized result and adds a ranking.
		-- RANK() adds analytical information without changing the number of rows.
			-- Final, RANK is a window function that assigns rankings to the resulting rows based on a specified 
			-- order without further aggregating the data.
SELECT
    customer_name,
    ROUND(SUM(sales),2) AS total_sales,
    RANK() OVER (ORDER BY SUM(sales) DESC) AS sales_rank
FROM superstore
GROUP BY customer_name
ORDER BY sales_rank
LIMIT 10;

-- DENSE_RANK() 
	-- No gaps.
SELECT
    customer_name,
    ROUND(SUM(sales),2) AS total_sales,
    DENSE_RANK() OVER (ORDER BY SUM(sales) DESC) AS sales_rank
FROM superstore
GROUP BY customer_name
ORDER BY sales_rank
LIMIT 10;

-- ROW_NUMBER()
-- Did the top 10 results change?
	-- No
-- In what business scenario would you use:
	-- RANK(): Use RANK() when ties should receive the same rank.
	-- ROW_NUMBER(): Use ROW_NUMBER() when every row must have a unique position, even if values are tied.
SELECT
    customer_name,
    ROUND(SUM(sales),2) AS total_sales,
    ROW_NUMBER() OVER (ORDER BY SUM(sales) DESC) AS row_num
FROM superstore
GROUP BY customer_name
ORDER BY row_num
LIMIT 10;

-- ROW_NUMBER()
	-- If A and B have exactly the same sales, who gets 1 and who gets 2?
	-- PostgreSQL chooses based on the ordering available, 
	-- and if the ORDER BY values are tied, the result can be arbitrary/non-deterministic unless you add another sorting column.
-- when many customers have the same sales.
-- because now the ranking is deterministic and repeatable.
-- A better approach is:
SELECT
    customer_name,
    ROUND(SUM(sales),2) AS total_sales,
    ROW_NUMBER() OVER (ORDER BY SUM(sales) DESC, customer_name) AS row_num
FROM superstore
GROUP BY customer_name
ORDER BY row_num
LIMIT 10;


-- CASE WHEN
-- Categorize orders into Loss, Profit
SELECT customer_name, sub_category, sales, profit,
    CASE
        WHEN profit < 0 THEN 'Loss'
        ELSE 'Profit'
    END AS profit_status
FROM superstore
ORDER BY profit;

-- CASE WHEN
-- Categorize orders into High, Medium, and Low profit.
SELECT customer_name, profit,
    CASE
        WHEN profit < 0 THEN 'Loss'
        WHEN profit BETWEEN 0 AND 100 THEN 'Low Profit'
        WHEN profit BETWEEN 100 AND 500 THEN 'Medium Profit'
        ELSE 'High Profit'
    END AS profit_category
FROM superstore;


-- 2. Date Functions
SELECT customer_name, order_date,
    EXTRACT(YEAR FROM order_date) AS order_year
FROM superstore;

SELECT customer_name, order_date,
    EXTRACT(MONTH FROM order_date) AS order_month
FROM superstore;

-- DATE_TRUNC moves the date to the beginning of the specified period.
-- This is how analysts create monthly sales trends.
SELECT
    DATE_TRUNC('month', order_date) AS month,
    ROUND(SUM(sales),2) AS sales
FROM superstore
GROUP BY month
ORDER BY month;

-- Which year had the highest sales?
	-- 2017
-- Which year had the highest profit?
	-- 2017
-- Did sales generally increase over time?
	-- Although sales experienced a slight decline in 2015, profitability continued to improve. 
	-- From 2016 onward, both sales and profit showed strong growth, reaching their highest levels in 2017.
-- Which is more important, Sales Growth or Profit Growth?
	-- Both are important, but profit growth is ultimately more meaningful because it reflects how much money 
	-- the company actually retains after costs. A company can increase sales while still losing money.
-- If you were presenting this to management, what would be your one-sentence conclusion?
	-- The company demonstrated strong year-over-year growth, with both sales and profit reaching their 
	-- highest levels in 2017, indicating successful business expansion and improved financial performance.
SELECT
    EXTRACT(YEAR FROM order_date) AS year,
    ROUND(SUM(sales),2) AS sales,
    ROUND(SUM(profit),2) AS profit
FROM superstore
GROUP BY year
ORDER BY year;

-- Find Top 5 Customers by Profit
-- Requirements: customer_name, total_sales, total_profit, profit_rank
-- Use: GROUP BY RANK()
-- A manager would care because:
	-- These customers contribute significantly to company profitability and 
	-- could be targeted for retention, loyalty programs, and premium offerings.
-- Why did you use RANK() instead of ORDER BY profit DESC LIMIT 5?
	-- ORDER BY and LIMIT can show the top 5 records, but RANK() explicitly provides the ranking position 
	-- and handles ties in a meaningful way. It also makes the query easier to extend for Top N analyses.
SELECT
    customer_name,
    ROUND(SUM(sales),2) AS total_sales,
	ROUND(SUM(profit),2) AS total_profit,
    RANK() OVER (ORDER BY SUM(profit) DESC) AS profit_rank
FROM superstore
GROUP BY customer_name
ORDER BY profit_rank
LIMIT 5;

-- Average_orders_per_customer
-- Average_products_per_order
-- Added missing comma and multiplied by 1.0 to ensure float/decimal division
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT customer_id) AS total_customers,
    COUNT(DISTINCT order_id) * 1.0 / COUNT(DISTINCT customer_id) AS Average_orders_per_customer, 
    COUNT(*) * 1.0 / COUNT(DISTINCT order_id) AS Average_products_per_order
FROM superstore;

-- avg_shipping_days
SELECT
    ship_mode,
    ROUND(AVG(ship_date - order_date),2) AS avg_shipping_days
FROM superstore
GROUP BY ship_mode
ORDER BY avg_shipping_days;

SELECT * FROM superstore
ORDER BY row_id;


