-- ============================================================================
-- SUPERSTORE SALES PERFORMANCE ANALYSIS
-- PostgreSQL Business Intelligence & Data Analysis Project
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. DATABASE SETUP & INITIALIZATION
-- ----------------------------------------------------------------------------

-- Create the main 'superstore' table with appropriate data types and constraints
CREATE TABLE superstore (
    row_id INTEGER PRIMARY KEY,
    
    order_id VARCHAR(20) NOT NULL,
    order_date DATE NOT NULL,
    ship_date DATE NOT NULL,
    
    ship_mode VARCHAR(50),
    
    customer_id VARCHAR(20) NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    
    segment VARCHAR(50),
    
    country VARCHAR(50),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    region VARCHAR(50),
    
    product_id VARCHAR(50) NOT NULL,
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_name VARCHAR(255),
    
    sales NUMERIC(10,2) NOT NULL,
    quantity INTEGER NOT NULL,
    discount NUMERIC(4,2) NOT NULL,
    profit NUMERIC(10,2) NOT NULL
);

-- Quick validation check to confirm table creation
SELECT * FROM superstore;

-- Import the raw dataset from a local CSV file using PostgreSQL COPY command
COPY superstore (row_id, order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, country, city, state, postal_code, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit)
FROM 'E:\All My Study\Data Analytics Projects\Sales Performance Dashboard\01 data\Sample - Superstore - csv3.csv'
DELIMITER ','
CSV HEADER;

-- Post-import validation checks to review the structure and sample data
SELECT * FROM superstore;

-- ----------------------------------------------------------------------------
-- 2. HIGH-LEVEL PERFORMANCE METRICS & OVERALL HEALTH
-- ----------------------------------------------------------------------------

-- Calculate Global KPI Metrics: Total Sales and Total Profit
-- Insights: Total Sales = $2,297,201.07 | Total Profit = $286,397.79
SELECT
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore;

-- Calculate Global Corporate Profit Margin % 
-- Purpose: Evaluate overall business health and financial efficiency
SELECT
    ROUND(SUM(profit)/SUM(sales)*100,2) AS profit_margin_pct
FROM superstore;


-- ----------------------------------------------------------------------------
-- 3. REGIONAL ANALYSIS
-- ----------------------------------------------------------------------------

-- Aggregate Sales and Profit across Geographic Regions 
SELECT
    region,
    ROUND(SUM(sales),2) AS sales,
    ROUND(SUM(profit),2) AS profit
FROM superstore
GROUP BY region
ORDER BY sales DESC;

-- Deep-Dive Region Efficiency: Performance Metrics sorted by Profit Margin %
-- Business Insight: The West contributes ~32% of total company sales and generates 
-- the highest absolute profit, making it the most critical region for growth initiatives.
SELECT
    region,
    ROUND(SUM(sales),2) AS sales,
    ROUND(SUM(profit),2) AS profit,
    ROUND((SUM(profit)/SUM(sales))*100,2) AS profit_margin_pct
FROM superstore
GROUP BY region
ORDER BY profit_margin_pct DESC;

-- Count total order-line entries generated by each geographical region
SELECT region, COUNT(*)
FROM superstore
GROUP BY region;


-- ----------------------------------------------------------------------------
-- 4. PRODUCT & CATEGORY METRICS (PROFITABILITY DRIVERS)
-- ----------------------------------------------------------------------------

-- Find the most profitable product categories
SELECT
    category,
    ROUND(SUM(sales),2) AS sales,
    ROUND(SUM(profit),2) AS profit
FROM superstore
GROUP BY category
ORDER BY profit DESC;

-- Identify underperforming and loss-making Sub-Categories hurting the business bottom line
SELECT
    sub_category,
    ROUND(SUM(profit),2) AS profit
FROM superstore
GROUP BY sub_category
ORDER BY profit ASC;

-- Filtering via HAVING: Show only top-performing major categories with profit > $50,000
SELECT
    category,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY category
HAVING SUM(profit) > 50000
ORDER BY total_profit DESC;

-- Filtering via HAVING: Target loss-making sub-categories for strategic review
-- Action Item: Analyze discount levels, sales volumes, and regional performance to fix the leak.
SELECT
    sub_category,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY sub_category
HAVING SUM(profit) < 0
ORDER BY total_profit;

-- Evaluate Sub-Categories on absolute profit performance
SELECT
    sub_category,
    ROUND(SUM(sales),2) AS sales,
    ROUND(SUM(profit),2) AS profit
FROM superstore
GROUP BY sub_category
ORDER BY profit ASC;

-- Evaluate Sub-Categories by Profit Margin Efficiency %
-- Business Insight: "Tables" generated over $206,000 in sales but produced a net loss 
-- of $17,725 (-8.56% margin). Requires immediate price optimization or discount reduction.
SELECT
    sub_category,
    ROUND(SUM(sales),2) AS sales,
    ROUND(SUM(profit),2) AS profit,
    ROUND((SUM(profit)/SUM(sales))*100,2) AS profit_margin_pct
FROM superstore
GROUP BY sub_category
ORDER BY profit_margin_pct;


-- ----------------------------------------------------------------------------
-- 5. ADVANCED ANALYTICAL QUERIES (CTES & WINDOW FUNCTIONS)
-- ----------------------------------------------------------------------------

-- Common Table Expression (CTE): Identify high-value categories performing above average
-- Insight: "Office Supplies" ($122,490.88) and "Technology" ($145,455.66) exceed the average.
WITH category_profit AS (
    SELECT
        category,
        SUM(profit) AS total_profit
    FROM superstore
    GROUP BY category
)
SELECT *
FROM category_profit
WHERE total_profit >
(
    SELECT AVG(total_profit)
    FROM category_profit
);

-- Analytical Ranking: Rank Top 10 Customers by total sales volume using RANK()
-- Behavior: Leaves gaps in rank numbering if duplicate values exist (Standard Olympic Rank).
SELECT
    customer_name,
    ROUND(SUM(sales),2) AS total_sales,
    RANK() OVER (ORDER BY SUM(sales) DESC) AS sales_rank
FROM superstore
GROUP BY customer_name
ORDER BY sales_rank
LIMIT 10;

-- Analytical Ranking: Rank Top 10 Customers by sales volume using DENSE_RANK()
-- Behavior: Consecutive rank numbering with no structural ranking gaps.
SELECT
    customer_name,
    ROUND(SUM(sales),2) AS total_sales,
    DENSE_RANK() OVER (ORDER BY SUM(sales) DESC) AS sales_rank
FROM superstore
GROUP BY customer_name
ORDER BY sales_rank
LIMIT 10;

-- Analytical Ranking: Rank Top 10 Customers using ROW_NUMBER()
-- Behavior: Assigns a strict sequential integer to every row regardless of duplicate values.
SELECT
    customer_name,
    ROUND(SUM(sales),2) AS total_sales,
    ROW_NUMBER() OVER (ORDER BY SUM(sales) DESC) AS row_num
FROM superstore
GROUP BY customer_name
ORDER BY row_num
LIMIT 10;

-- ----------------------------------------------------------------------------
-- 6. OPERATIONAL METRICS & CUSTOMER BEHAVIOR
-- ----------------------------------------------------------------------------

-- Baseline Volume Counts: Total order-lines, distinct orders, and unique customers
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT customer_id) AS total_customers
FROM superstore;

-- Operational Efficiency: Multi-metric evaluation of customer buying behaviors
-- Business Insight: COUNT(*) tracks distinct product-line records while COUNT(DISTINCT) captures 
-- unique instances, validating that single orders regularly bundle multiple line items.
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT customer_id) AS total_customers, 
    ROUND(COUNT(DISTINCT order_id) * 1.0 / COUNT(DISTINCT customer_id),2) AS Average_orders_per_customer, 
    ROUND(COUNT(*) * 1.0 / COUNT(DISTINCT order_id),2) AS Average_products_per_order
FROM superstore;

-- Supply Chain Efficiency: Average processing time (days) grouped by Fulfillment/Shipping Mode
SELECT
    ship_mode,
    ROUND(AVG(ship_date - order_date),2) AS avg_shipping_days
FROM superstore
GROUP BY ship_mode
ORDER BY avg_shipping_days;

-- Identify Top 5 Strategic Customers by Absolute Profit contribution using Window Functions
-- Management Strategy: Highly critical cohort targeted for customer retention and loyalty workflows.
SELECT
    customer_name,
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit,
    RANK() OVER (ORDER BY SUM(profit) DESC) AS profit_rank
FROM superstore
GROUP BY customer_name
ORDER BY profit_rank
LIMIT 5;


-- ----------------------------------------------------------------------------
-- 7. CONDITIONAL CLASSIFICATION & SEGMENTATION
-- ----------------------------------------------------------------------------

-- Binary Classification: Classify orders explicitly into 'Profit' or 'Loss' categories
SELECT customer_name, sub_category, sales, profit,
    CASE
        WHEN profit < 0 THEN 'Loss'
        ELSE 'Profit'
    END AS profit_status
FROM superstore
ORDER BY profit;

-- Granular Tiers: Segment orders into refined descriptive revenue buckets
SELECT customer_name, profit,
    CASE
        WHEN profit < 0 THEN 'Loss'
        WHEN profit BETWEEN 0 AND 100 THEN 'Low Profit'
        WHEN profit BETWEEN 100 AND 500 THEN 'Medium Profit'
        ELSE 'High Profit'
    END AS profit_category
FROM superstore;


-- ----------------------------------------------------------------------------
-- 8. DATE & TIME TREND ANALYSIS
-- ----------------------------------------------------------------------------

-- Time-Series Extraction: Pull Year element out from baseline Order Dates
SELECT customer_name, order_date,
    EXTRACT(YEAR FROM order_date) AS order_year
FROM superstore;

-- Time-Series Extraction: Pull Month element out from baseline Order Dates
SELECT customer_name, order_date,
    EXTRACT(MONTH FROM order_date) AS order_month
FROM superstore;

-- Macro-Trend Aggregations: Roll metrics back to the first day of each month for trend lines
SELECT
    DATE_TRUNC('month', order_date) AS month,
    ROUND(SUM(sales),2) AS sales
FROM superstore
GROUP BY month
ORDER BY month;

-- YoY Corporate Growth Evaluation: Annual Performance Analysis
-- Executive Summary: Strong year-over-year expansion. While 2015 experienced a brief flatline, 
-- profitability scaling recovered strongly. Both revenue metrics peaked significantly in 2017.
SELECT
    EXTRACT(YEAR FROM order_date) AS year,
    ROUND(SUM(sales),2) AS sales,
    ROUND(SUM(profit),2) AS profit
FROM superstore
GROUP BY year
ORDER BY year;

-- Final database row-level inspection check
SELECT * FROM superstore
ORDER BY row_id;
